version: "3.9"
services:
  etcd:
    image: pachyderm/etcd:v3.5.2-arm64
    container_name: etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "2379:2379"
      - "2380:2380"
    user: root
    volumes:
      - "./etcd/conf:/opt/bitnami/etcd/conf"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/conf"

  e3w:
    image: soyking/e3w:v0.1.1
    container_name: e3w
    ports:
      - "8080:8080"
    volumes:
      - "./e3w/conf:/app/conf"

  etcdv3-browser:
    # https://github.com/gohutool/boot4go-etcdv3-browser
    # Default Username/Password ginghan/123456
    # Add '192.168.1.101 etcdv3-broswer.joinsunsoft.com' to /etc/hosts/hosts file
    image: joinsunsoft/etcdv3-browser:0.9.0
    container_name: etcdv3-browser
    ports:
      - "9980:80"