version: "3.9"
services:
  etcd:
    hostname: etcd
    image: pachyderm/etcd:v3.5.2-arm64
    container_name: etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "2379:2379"
      - "2380:2380"
    user: root
    volumes:
      - "./etcd/conf:/opt/bitnami/etcd/conf"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/conf"

  e3w:
    hostname: e3w
    image: soyking/e3w:v0.1.1
    container_name: e3w
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - "./e3w/conf:/app/conf"