version: '3.9'
services:
  caddy:
    image: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - :/etc/caddy/Caddyfile
      - :/data
      - :/storage
      - :/config