version: '3.9'

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

  dingtalk:
    image: timonwong/prometheus-webhook-dingtalk:latest
    container_name: dingtalk
    volumes:
      - "./dingtalk/config.yml:/etc/prometheus-webhook-dingtalk/config.yml:ro"
    ports:
      - "8060:8060"
    entrypoint: /bin/prometheus-webhook-dingtalk --ding.profile="webhook1=https://oapi.dingtalk.com/robot/send?access_token=***********"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - "./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro"
      - "./alertmanager/templates:/etc/alertmanager/templates"
      - "./alertmanager/data:/alertmanager"
    ports:
      - "9093:9093"
      - "9094:9094"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/rules:/etc/prometheus/rules"
      - "./prometheus/data:/prometheus"
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    # admin admin
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - "./grafana/data:/var/lib/grafana"
    ports:
      - "3000:3000"
