version: '3.9'
services:
  portainer:
    # UserName : admin
    # Password : yang+fh
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer/data:/data"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"

  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./agent/volumes:/var/lib/docker/volumes"
    ports:
      - "9001:9001"