version: '3.9'
services:
  # 用户名：yangxk
  # 密码：123456
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    restart: always
    ports:
      - "10022:22"
      - "13000:3000"
    volumes:
      - "./gogs/data:/data"
      - "./gogs/backup:/backup"
